dist: bionic
branches:
  except:
  - "/^wip/"
sudo: true
language: node_js
node_js:
- '8'
- '10'
before_install:
- sudo apt-get update -q -y
- sudo apt-get install -y cvc4 libcvc4-dev
script:
- yarn lint
- yarn test
after_success:
- yarn coverage
